name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Subir APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: StickerPop-APK
          path: app/build/outputs/apk/debug/*.apk