name: Build StickerPop APK

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Preparar Gradle
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Buscar APK
        run: find app/build/outputs -type f -name "*.apk"

      - name: Crear Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: StickerPop v1.0.${{ github.run_number }}
          generate_release_notes: true
          files: app/build/outputs/apk/debug/app-debug.apk
